require("paper")
require("sugar")
require("svg.js")
require("svg.draggable.js")
require("svg.pathmorphing.js")
require("text-to-svg")
require("svg.easing.js")
require("./library/svgUtils.js");
require("./library/svg.topath.js");
